tools:
    external_code_coverage: false

filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'build/*'
        - 'log/*'
        - 'tests/*'
        - 'vendor/*'

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
